{
 "title": "Hardcoders",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-node" },
   {
    "name": "container",
    "query": "tp1_node_1, tp1_node_2, tp1_node_3, tp1_cadvisor_1, tp1_grafana_1, tp1_graphite_1,  tp1_nginx_1, tp1_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenarios Created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "target": "scale(alias(stats.gauges.$server.scenariosCreated, 'Count'), 0.1)"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "target": "scale(alias(stats.gauges.$server.rps.count, 'Count'), 0.1)"
    }
   ]
  },
  {
   "title": "Latency P50 and P95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.artillery-node.latency.p95, 'latency p95')"
    },
    {
     "target": "alias(stats.gauges.artillery-node.latency.p50, 'latency p50')"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.requestsCompleted, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    }
   ]
  },
  {
   "title": "CPU Usage Node 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp1_node_1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    }
   ]
  },
  {
   "title": "Memory Consumption Node 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.cadvisor.tp1_node_1.memory_working_set, 'Memory')"
    }
   ]
  },
  {
   "title": "CPU Usage Bbox",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp1_bbox_1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    }
   ]
  },
  {
   "title": "Memory Consumption Bbox",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.cadvisor.tp1_bbox_1.memory_working_set, 'Memory')"
    }
   ]
  },
  {
   "title": "CPU Usage NGINX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.tp1_nginx_1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    }
   ]
  },
  {
   "title": "Memory Consumption NGINX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.cadvisor.tp1_nginx_1.memory_working_set, 'Memory')"
    }
   ]
  }
 ]
}